import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faArrowLeft,
  faArrowRight,
  faCircleXmark,
  faArrowRotateLeft,
  faEye,
  faEyeSlash,
  faMagnifyingGlass,
  faPlus,
  faTerminal,
  faKey,
  faCheck,
  faInfoCircle,
  faSquareCheck,
  faTriangleExclamation,
  faHouse,
  faFolder,
  faFile,
  faFilePdf,
  faFileZipper,
  faFileCode,
  faFileCsv,
  faFileLines,
  faFileImage,
  faFileVideo,
  faBoxArchive,
} from '@fortawesome/free-solid-svg-icons';
import { faSquare } from '@fortawesome/free-regular-svg-icons';
import { faCss3, faDropbox, faHtml5, faJsSquare, faMarkdown } from '@fortawesome/free-brands-svg-icons';

// Add the icons used by the whole application to the library, allowing to use globally
library.add(
  faKey,
  faCheck,
  faArrowLeft,
  faCircleXmark,
  faArrowRight,
  faArrowRotateLeft,
  faEye,
  faEyeSlash,
  faMagnifyingGlass,
  faPlus,
  faTerminal,
  faDropbox,
  faInfoCircle,
  faSquareCheck,
  faSquare,
  faTriangleExclamation,
  faHouse,
  faFolder,
  faFile,
  faFilePdf,
  faJsSquare,
  faFileZipper,
  faMarkdown,
  faCss3,
  faFileCode,
  faHtml5,
  faFileCsv,
  faFileLines,
  faFileImage,
  faFileVideo,
  faBoxArchive,
);
